# Generated by Django 4.2.4 on 2023-09-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('Impuesto', models.IntegerField()),
                ('Size', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=255)),
                ('inventario', models.IntegerField()),
                ('bodega', models.IntegerField()),
                ('Marca', models.CharField(max_length=50)),
                ('Detalle', models.CharField(max_length=200)),
                ('events_id', models.BigIntegerField(blank=True, null=True)),
                ('categoria_id', models.BigIntegerField(blank=True, null=True)),
                ('subcategoria_id', models.IntegerField(blank=True, null=True)),
                ('Botones', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('CodigoPeso', models.IntegerField()),
                ('FactorConversion', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='photos/banner')),
                ('fechainicial', models.DateTimeField()),
                ('fechaFinal', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Desactivdado', 'Desactivdado')], default='Activo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductViewBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.banner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
